In [1]:
import datetime as dt
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
import seaborn as sns
import yfinance as yf

In [2]:
tickerSymbols = ['TSLA', 'AAPL','MSFT','NVDA','AMZN','AMD','GME']

TSLA = yf.Ticker(tickerSymbols[0])
AAPL = yf.Ticker(tickerSymbols[1])
MSFT = yf.Ticker(tickerSymbols[2])
NVDA = yf.Ticker(tickerSymbols[3])
AMZN = yf.Ticker(tickerSymbols[4])
AMD = yf.Ticker(tickerSymbols[5])
GME = yf.Ticker(tickerSymbols[6])

In [3]:
TSLA_df = TSLA.history(period = '3m', start = '2022-07-01', end = '2022-10-01')
AAPL_df = AAPL.history(period = '3m', start = '2022-07-01', end = '2022-10-01')
MSFT_df = MSFT.history(period = '3m', start = '2022-07-01', end = '2022-10-01')
NVDA_df = NVDA.history(period = '3m', start = '2022-07-01', end = '2022-10-01')
AMZN_df = AMZN.history(period = '3m', start = '2022-07-01', end = '2022-10-01')
AMD_df = AMD.history(period = '3m', start = '2022-07-01', end = '2022-10-01')
GME_df = GME.history(period = '3m', start = '2022-07-01', end = '2022-10-01')

In [4]:
TSLA = TSLA_df['Close']
AAPL = AAPL_df['Close']
MSFT = MSFT_df['Close']
NVDA = NVDA_df['Close']
AMZN = AMZN_df['Close']
AMD = AMD_df['Close']
GME = GME_df['Close']

In [5]:
stocks_df = pd.concat([TSLA, AAPL, MSFT, NVDA, AMZN, AMD, GME], axis = 'columns', join = 'inner')
stocks_df.columns = ['TSLA', 'AAPL', 'MSFT', 'NVDA', 'AMZN', 'AMD', 'GME']
stocks_df.tail()

,TSLA,AAPL,MSFT,NVDA,AMZN,AMD,GME
Date,,,,,,,
2022-09-26,276.010010,150.770004,237.449997,122.279999,115.150002,66.300003,24.480000
2022-09-27,282.940002,151.759995,236.410004,124.129997,114.410004,67.169998,26.129999
2022-09-28,287.809998,149.839996,241.070007,127.360001,118.010002,68.360001,27.309999
2022-09-29,268.209991,142.479996,237.500000,122.199997,114.800003,64.139999,25.459999
2022-09-30,265.250000,138.199997,232.899994,121.389999,113.000000,63.360001,25.129999

In [6]:
# percentage Change
stocks_df1 = stocks_df.pct_change().dropna()
stocks_df1.head()

,TSLA,AAPL,MSFT,NVDA,AMZN,AMD,GME
Date,,,,,,,
2022-07-05,0.025536,0.018930,0.012597,0.030366,0.035962,0.020768,-0.025847
2022-07-06,-0.005721,0.009607,0.012783,0.011093,0.007313,0.001995,-0.023289
2022-07-07,0.055279,0.023999,0.008227,0.048116,0.017493,0.052422,0.150643
2022-07-08,0.025435,0.004715,-0.002757,-0.001261,-0.006791,0.000630,-0.048697
2022-07-11,-0.065480,-0.014758,-0.011769,-0.043314,-0.032803,-0.030246,0.012059

In [7]:
# standard deviation of each stock
stocks_sd = stocks_df.std()

In [8]:
# Annualized Volatility of Each stock
Annualized_volatility = stocks_df.std() * np.sqrt(252)

In [9]:
# Beta against ETFS
#SPY, IWM, DIA need to get standard deviation of the etfs 
ETFtickers = ['SPY','IWM','DIA']
SPY = yf.Ticker(tickerSymbols[0])
IWM = yf.Ticker(tickerSymbols[1])
DIA = yf.Ticker(tickerSymbols[2])

SPY_df = SPY.history(period = '1y', start = '2021-10-01', end = '2022-10-01')
IWM_df = IWM.history(period = '1y', start = '2021-10-01', end = '2022-10-01')
DIA_df = DIA.history(period = '1y', start = '2021-10-01', end = '2022-10-01')







#etfs_df = pd.concat([SPY_df, IWM_df, DIA_df], axis = 'columns', join = 'inner')
#etfs_df.columns = ['SPY','IWM','DIA']
#etfs_df.tail()

In [10]:
#Average weekly Drawdown
#TSLA

In [11]:
# portfolio weight Stock value / total portfolio value *100

In [12]:
#Cost of stocks
#stock_price 'TSLA', 'AAPL','MSFT','NVDA','AMZN','AMD','GME'
tsla_stock_price = yf.Ticker('tsla').info['regularMarketPrice']
aapl_stock_price = yf.Ticker('aapl').info['regularMarketPrice']
msft_stock_price = yf.Ticker('msft').info['regularMarketPrice']
nvda_stock_price = yf.Ticker('nvda').info['regularMarketPrice']
amzn_stock_price = yf.Ticker('amzn').info['regularMarketPrice']
amd_stock_price = yf.Ticker('amd').info['regularMarketPrice']
gme_stock_price = yf.Ticker('gme').info['regularMarketPrice']

In [13]:
#tsla_stock_price   $243.44
#aapl_stock_price  $142.66
#msft_stock_price  $240.61
#nvda_stock_price  $125.81
#amzn_stock_price  $116.3415
#amd_stock_price   $66.495
#gme_stock_price   $25.29
tsla_stock_price / (tsla_stock_price + aapl_stock_price + msft_stock_price + 
                    nvda_stock_price + amzn_stock_price + amd_stock_price + gme_stock_price) 
# portfolio weight for tesla -> 0.2534125702170069 
aapl_stock_price / (tsla_stock_price + aapl_stock_price + msft_stock_price + 
                    nvda_stock_price + amzn_stock_price + amd_stock_price + gme_stock_price) 
# portfolio weight for aapl -> 0.148504096562431

msft_stock_price / (tsla_stock_price + aapl_stock_price + msft_stock_price + 
                    nvda_stock_price + amzn_stock_price + amd_stock_price + gme_stock_price) 
# portfolio weight for msft = 0.25046663867858215

0.2508344511339177